var totalStations = [
    "STATION _ 1",
    "STATION _ 2",
    "STATION _ 3",
    "STATION _ 4",
    "STATION _ 5",
    "STATION _ 6",
    "STATION _ 7",
    "STATION _ 8",
    "STATION _ 9",
    "STATION _ 10",
    "STATION _ 11",
    "STATION _ 12",
    "ನಿಲ್ದಾಣ _ 13",
    "స్టేషన్ _ 14",
    "स्टेशन _ 15",
    "স্টেশন _ 16",
    "நிலையம் _ 17",
    "സ്റ്റേഷൻ _ 18",
    "स्टेशन _ 19",
    "ଷ୍ଟେସନ | _ 20",
    "اسٹیشن _ 21",
    "STATION _ 22",
    "STATION _ 23",
    "STATION _ 24"
];